---
title: "analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggmap)
library(janitor)
```

# crime number

```{r}
MD_Crime %>%
  group_by(`Crime Name2`) %>%
  count() %>%
  arrange(desc(n)) %>%
  as.data.frame()

MD_Crime %>%
  group_by(`Crime Name1`) %>%
  count() %>%
  arrange(n) 

MD_Crime3 <- MD_Crime %>%
  group_by(`Crime Name2`) %>%
  summarise(count = n()) %>%
  filter(count > 1000) 

MD_Crime %>%
  filter(`Crime Name1` == "Crime Against Person")

MD_Crime %>%
  filter(`Crime Name2` == "Larceny" | `Crime Name2` == "Damage Property" | `Crime Name2` ==  "Assault" | `Crime Name2` == "Drugs"| `Crime Name2` ==  "Fraud") 
  
unique(MD_Crime$`Crime Name2`)

https://stringr.tidyverse.org/reference/str_trim.html
clean_names()

MD_Crime %>% 
  select(`Crime Name2`, Place1, Place2) %>%
  filter(`Crime Name2` == "Rape") %>%
  group_by(Place1, Place2) %>%
  count() %>%
  arrange(desc(n))
```

# crime rate by city

```{r}
MD_Crime %>%
  group_by(City)%>%
  count() %>%
  arrange(desc(n))
10615/30587 = 0.3470429
4501/30587 = 0.147154

```
```{r, fig.height=3, fig.width=16}
MD_Crime4 <- MD_Crime %>%
  filter(`Crime Name2` == "Drugs" | `Crime Name2` == "Damage Property" | `Crime Name2` ==  "Assault") %>%
  filter(Longitude != 0) %>%
  group_by(`Crime Name2`)%>%
  mutate(group = 1174,
         subregion = "montgomery")

MD <- map_data("county") %>%
  filter(region == "maryland") %>%
  rename(Longitude = long,
         Latitude = lat) 
ggplot(data = MD, mapping = aes(x = Longitude, y = Latitude, group = group, fill = subregion)) +
   geom_polygon(fill = "white", color = "black") + 
   facet_zoom(xlim = c(-76.90530, -77.51680),
               ylim = c(38.93900, 39.34210)) #+
   geom_point(data = MD_Crime4, mapping = aes(x=Longitude, y=Latitude, color = `Crime Name2`, alpha = 0.05)) +
   theme(legend.title = element_blank(),
         legend.position = "bottom") +
  scale_color_manual(values = color) +
  ggtitle("Location and Density of Crimes in Montgomery County in Maryland, 2020")


#+
  geom_text(aes(y = 38.994373, x = -77.029778, label = "Silver Spring")) +
  geom_text(aes(y = 39.1440, x = -77.2016, label = "Gaithersburg")) +
  geom_text(aes(y = 39.0840, x = -77.1528, label = "Rockville"))

  

color <- c("Assault" = "pink", "Damage Property" = "lightgoldenrod", "Drugs" = "lightblue")

MD_Crime5 <- MD_Crime4 %>% mutate(across(is.numeric, ~ round(., 2))) %>%
  filter(Longitude != 0)
MD_Crime5 <- MD_Crime5 %>%
  group_by(`Crime Name2`, `Longitude`, `Latitude`) %>%
  count() %>%
  mutate(group = 1174,
         subregion = "montgomery")

MD_Crime %>%
  group_by(`Crime Name1`, `Crime Name2`) %>%
  count() %>%
  group_by(`Crime Name1`) %>%
  arrange(desc(n))

MD_Crime %>%
  group_by(City) %>%
  count() %>%
  arrange(desc(n))

```






# Location
```{r}
MD_Crime %>%
  filter(Latitude != 0) %>%
  ggplot(mapping = aes(x = Latitude, y = Longitude)) +
  geom_hex() +
  scale_fill_distiller(palette = "RdYlBu") +
  ggtitle("Location And Density of Crimes in Maryland in 2020")

library(maps)

us_states <- map_data("state") %>%
  filter(region == "maryland") %>%
  rename(Longitude = long,
         Latitude = lat)


us_counties <- map_data("county") %>%
  filter(region == "maryland" & subregion == "montgomery") %>%
  rename(Longitude = long,
         Latitude = lat)

MD <- map_data("county") %>%
  filter(region == "maryland") %>%
  rename(Longitude = long,
         Latitude = lat) 
ggplot(data = MD, mapping = aes(x = Longitude, y = Latitude, group = group, fill = subregion)) +
   geom_polygon(fill = "white", color = "black") + 
   facet_zoom(xlim = c(-76.90530, -77.51680),
               ylim = c(38.93900, 39.34210)) +
   geom_point(data = MD_Crime4, mapping = aes(x=Longitude, y=Latitude, color = `Crime Name1`))

MD_Crime4 <- MD_Crime %>%
  filter(`Crime Name2` == "Larceny" | `Crime Name2` == "Damage Property" | `Crime Name2` ==  "Assault") %>%
  filter(Longitude != 0) %>%
  group_by(`Crime Name2`)%>%
  mutate(group = 1174,
         subregion = "montgomery")
  

library(ggforce)


```


# Date and Time
```{r}

MD_Crime %>%
  mutate(Date = `Dispatch Date` == `Start Date`) %>%
  mutate(Date = case_when(Date = TRUE ~ "Same Date",
                          Date = FALSE ~ "Different Date")) %>%
  group_by(Date) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count)) 
# all on the same date

MD_Crime %>%
  mutate(Date = `Dispatch Date` == `Start Date`) %>%
  filter(Date == TRUE) %>%
  mutate(Dispatch = case_when(`Start Time` < `Dispatch Time` ~ "After",
                           `Start Time` > `Dispatch Time` ~ "Before",
                           `Start Time` == `Dispatch Time` ~ "On Time")) %>%
  group_by(Dispatch)  %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count)) 
```
# Date
```{r}
 MD_Crime %>%
 group_by(`Dispatch Date`) %>%
  count() %>%
  arrange(desc(n))
  ggplot(aes(x = `Dispatch Date`, y = n), color = `Crime Name1`) +
  geom_line()
```
